name: Update Proxies Site

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск раз в 30 минут автоматически
  workflow_dispatch: # Оставляет кнопку ручного запуска в панели Actions

permissions:
  contents: write # Разрешение менять файлы в репозитории

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Копируем репозиторий
      uses: actions/checkout@v4

    - name: Настраиваем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Устанавливаем библиотеку для запросов
      run: pip install requests

    - name: Запуск сбора прокси и обновления сайта
      run: python proxy_parser.py

    - name: Сохранение изменений в GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git add proxies.txt
        git commit -m "Автоматическое обновление прокси и сайта [skip ci]" || echo "Нет изменений для коммита"
        git push
