name: Update Proxies Site

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.10'}
    
    # Кэшируем pip, чтобы не скачивать зависимости повторно
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        
    - run: pip install requests
    - run: python proxy_parser.py
    
    - name: Commit changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Update proxies and HTML [skip ci]" || echo "No changes"
        git push
